# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
---
# BlueBuild Recipe for CentOS Stream 10 - Lenovo AMD Laptops
# Target: Lenovo IdeaPad 5 15ALC05 (AMD Ryzen 5500U)
# DE: GNOME 47
#
# Build: bluebuild build ./recipes/recipe.yml

name: centos10-ideapad5-gnome
description: CentOS Stream 10 GNOME Desktop for Lenovo IdeaPad 5 15ALC05

base-image: quay.io/centos-bootc/centos-bootc
image-version: stream10

modules:
  # ========================================
  # BASE SYSTEM
  # ========================================
  - from-file: base-repos.yml

  - from-file: base-system.yml

  - from-file: hardware-amd-laptop.yml

  - from-file: networking.yml

  - from-file: audio-pipewire.yml

  - from-file: power-management.yml

  # ========================================
  # DESKTOP ENVIRONMENT - GNOME
  # ========================================
  - from-file: desktop-gnome.yml

  # ========================================
  # APPLICATIONS & TOOLS
  # ========================================
  - from-file: apps-browser.yml

  - from-file: apps-containers.yml

  - from-file: apps-server.yml

  # Optional - comment out if not needed
  - from-file: apps-dev.yml

  # ========================================
  # FINAL CONFIGURATION
  # ========================================
  - from-file: system-config.yml
